/*
 * This is an autogenerated file. Modifications
 * might not be persistent.
 */
namespace protoNNParam {

    /** Gamma for gaussian kernel */
    const PROGMEM float gamma = 0.001475;
    /** Low Dimensional Projection Matrix */
    const PROGMEM unsigned int featDim = 124;
    const PROGMEM unsigned int ldDim = 10;

    /**
    * Projectino Matrix (W)
    * d_cap x d flattened (dimension of 2D array)
    * ldDim x featDim
    */
    const PROGMEM  float ldProjectionMatrix[]  = {
	};
    
    /**
     * Prototypes (B)
     * m x d_cap flattened (dimension of 2D array)
     * numPrototypes x d_cap
     */
    const PROGMEM float prototypeMatrix[] = {
	};
    /** Number of prototypes (m) */
    const PROGMEM unsigned int numPrototypes = 20;
    
    /**
     * Prototype Lables (Z)
     * m x L (dimension of 2D array)
     * numLabels x numPrototypes
     */
    const PROGMEM float prototypeLabelMatrix[] = {
    };
    /** Number of output labels, (L). */
    const PROGMEM unsigned int numLabels = 10; // 0,1,2,3,4,5
    

};
    